# The URL the site will be built for
base_url = "https://cityanalytics.exchange"

# Site title and description
title = "City Analytics Exchange"
description = "For data workers in local government"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Theme to use
theme = "even"

# Generate RSS feed
generate_feeds = true

# Taxonomies
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"

[extra]

# Navigation menu
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/pages/about", name = "About"},
    {url = "$BASE_URL/pages/meetings", name = "Meetings"},
]

# Site title for the theme
even_title = "City Analytics Exchange"